### ISSUE TITLE
[Common] 멀티모듈에서의 yaml 파일 상속 문제

### ISSUE THREAD

**Issue by iyj6707** [prgrms-be-devcourse/BEDV1_OurHome#52]

**Comment by hanjo8813** [comment]
해결해줘잉~~~

**Comment by iyj6707** [comment]
yaml 파일이 인식되지 않을 경우 순서대로 하나씩 해 볼 것

1. build (망치 아이콘)
2. File > Invalidate caches
3. reload from disk
4. 재부팅 후 기도
